name: Deployment for MS-Windows
on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize ]
jobs:
  compile:
    strategy:
      matrix:
        config:
          - Release
          - Debug
    name: ${{ matrix.config }} Build
    runs-on: windows-latest
    steps:
    - name: Installing dependencies
      run: |
        $env:Path += ";C:\msys64\usr\bin"
        pacman.exe --noconfirm -Syyuu
        pacman.exe --noconfirm -Syyuu
        pacman.exe --noconfirm -S mingw-w64-x86_64-ninja mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-glew mingw-w64-x86_64-boost
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Compiler
      run: |
        $env:Path = "C:/msys64/mingw64/include;C:/msys64/mingw64/lib;C:/msys64/usr/bin;C:/msys64/mingw64/bin;$env:Path"
        $env:CC = "C:/msys64/mingw64/bin/gcc.exe"
        $env:CXX = "C:/msys64/mingw64/bin/g++.exe"
        mkdir $env:GITHUB_WORKSPACE\build
        cd $env:GITHUB_WORKSPACE\build
        cmake.exe -G Ninja .. -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DOPTION_BUILD_WEBSITE_TOOLS=OFF -DOPTION_BUILD_TRANSLATIONS=ON -DOPTION_BUILD_TESTS=ON -DOPTION_ASAN=OFF -DUSE_XDG=OFF -DOPTION_BUILD_CODECHECK=OFF -DUSE_FLTO_IF_AVAILABLE=OFF -DCMAKE_JOB_POOLS="linking=1" -DCMAKE_JOB_POOL_LINK=linking -DOPTION_BUILD_WINSTATIC=ON -DPNG_LIBRARY_RELEASE=C:/msys64/mingw64/lib/libpng.a -DSDL2_IMAGE_LIBRARY=C:/msys64/mingw64/lib/libSDL2_image.a -DZLIB_LIBRARY_RELEASE=C:/msys64/mingw64/lib/libz.a -DSDL2_TTF_LIBRARY=C:/msys64/mingw64/lib/libSDL2_ttf.a -DSDL2_MIXER_LIBRARY=C:/msys64/mingw64/lib/libSDL2_mixer.a -DSDL2MAIN_LIBRARY=C:/msys64/mingw64/lib/libSDL2main.a -DSDL2_LIBRARY=C:/msys64/mingw64/lib/libSDL2.a -DICU_UC_LIBRARY_RELEASE=C:/msys64/mingw64/lib/libicuuc.a -DICU_DT_LIBRARY_RELEASE=C:/msys64/mingw64/lib/libicudt.a -DINTL_LIBRARY=C:/msys64/mingw64/lib/libintl.a -DGLEW_LIBRARY=C:/msys64/mingw64/lib/libglew32.a
        cmake.exe --build .
        strip -sv ./src/widelands.exe
    - name: InnoSetup
      run: |
        cd $env:GITHUB_WORKSPACE
        # Environment variables needed by our InnoSetup script
        $env:MINGWPATH = "C:\msys64\mingw64\bin"
        $env:PLATFORM = "x64"
        $env:CONFIGURATION = "${{ matrix.config }}"
        $env:APPVEYOR_BUILD_FOLDER = $env:GITHUB_WORKSPACE
        $env:APPVEYOR_BUILD_VERSION = "Widelands-${{ github.sha }}-${{ matrix.config }}-x64"
        ISCC.exe /o$env:GITHUB_WORKSPACE /fWidelands-${{ github.sha }}-${{ matrix.config }}-x64 $env:GITHUB_WORKSPACE\utils\win32\innosetup\Widelands.iss
    - name: Uploading installer
      uses: actions/upload-artifact@v2
      with:
        name: Widelands 64-bit ${{ matrix.config }} Installer
        path: ${{ github.workspace }}\Widelands-${{ github.sha }}-${{ matrix.config }}-x64.exe
